# **Sentiment Analysis on IMDB Movie Reviews using LSTM**

In [0]:
from __future__ import print_function
from keras.preprocessing import sequence
from keras.models import Sequential
from keras.layers import Dense, Embedding
from keras.datasets import imdb
from keras.layers import LSTM
import numpy as np

max_features = 20000
maxlen = 80
batch_size = 200

In [21]:
(X_train, y_train), (X_test, y_test) = imdb.load_data(num_words=max_features)

17465344/17464789 [==============================] - 2s 0us/step


In [22]:
print(X_train.shape,y_train.shape)

(25000,) (25000,)


In [23]:
X_train

array([list([1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 2, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 2, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 19193, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 10311, 8, 4, 107, 117, 5952, 15, 256, 4, 2, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 12118, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19, 178, 32]),
       list([1, 194, 1153, 194, 82

In [24]:
for i in range(0,3):
  print(len(X_train[i]))

218
189
141


In [25]:
print('Pad sequences (samples x time)')
X_train = sequence.pad_sequences(X_train,maxlen=maxlen)
X_test = sequence.pad_sequences(X_test,maxlen=maxlen)

Pad sequences (samples x time)


In [26]:
print('X train shape: ',X_train.shape)
print('X_test shape',X_test.shape)

X train shape:  (25000, 80)
X_test shape (25000, 80)


In [27]:
X_train

array([[   15,   256,     4, ...,    19,   178,    32],
       [  125,    68,     2, ...,    16,   145,    95],
       [  645,   662,     8, ...,     7,   129,   113],
       ...,
       [  529,   443, 17793, ...,     4,  3586,     2],
       [  286,  1814,    23, ...,    12,     9,    23],
       [   97,    90,    35, ...,   204,   131,     9]], dtype=int32)

In [28]:
for i in range(0,3):
  print(len(X_train[i]))

80
80
80


In [33]:
print('Build Model')
model = Sequential()
model.add(Embedding(max_features,128))
model.add(LSTM(128,dropout=0.2,recurrent_dropout=0.2))
model.add(Dense(1,activation='sigmoid'))

model.compile(loss='binary_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

Build Model


In [34]:
print('Train')
model.fit(X_train,y_train,
          batch_size=batch_size,
          epochs = 3,
          validation_data=(X_test,y_test))

Train


/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/indexed_slices.py:434: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "


Train on 25000 samples, validate on 25000 samples
Epoch 1/3
25000/25000 [==============================] - 81s 3ms/step - loss: 0.4908 - accuracy: 0.7542 - val_loss: 0.3728 - val_accuracy: 0.8374
Epoch 2/3
25000/25000 [==============================] - 81s 3ms/step - loss: 0.3008 - accuracy: 0.8814 - val_loss: 0.3679 - val_accuracy: 0.8381
Epoch 3/3
25000/25000 [==============================] - 81s 3ms/step - loss: 0.2418 - accuracy: 0.9071 - val_loss: 0.4308 - val_accuracy: 0.8287


In [35]:
score ,acc = model.evaluate(X_test,y_test,batch_size=batch_size)
print('Test score',score)
print('Test Accuracy',acc)

25000/25000 [==============================] - 17s 672us/step
Test score 0.43078354334831237
Test Accuracy 0.828719973564148


# **Sentiment Analysis on Movie Reviews using LSTM RNN Model**

In [0]:
from gensim import corpora
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import SnowballStemmer

In [0]:
from keras.preprocessing import sequence
from keras.utils import np_utils
from keras.models import Sequential
from keras.layers import Dense, Dropout,Activation,Embedding
from keras.layers import LSTM
from keras.layers.convolutional import Conv1D
from keras.layers.convolutional import MaxPooling1D

In [0]:
train = pd.read_csv('/content/drive/My Drive/data/train.tsv',sep='\t',header=0)
test = pd.read_csv('/content/drive/My Drive/data/test.tsv',sep='\t',header=0)

In [42]:
train.shape, test.shape

((156060, 4), (66292, 3))

In [43]:
train.head()

PhraseId  ...  Sentiment
0         1  ...          1
1         2  ...          2
2         3  ...          2
3         4  ...          2
4         5  ...          2

[5 rows x 4 columns]

In [44]:
test.head()

PhraseId  SentenceId                                             Phrase
0    156061        8545  An intermittently pleasing but mostly routine ...
1    156062        8545  An intermittently pleasing but mostly routine ...
2    156063        8545                                                 An
3    156064        8545  intermittently pleasing but mostly routine effort
4    156065        8545         intermittently pleasing but mostly routine

In [0]:
raw_docs_train  = train['Phrase'].values
raw_docs_test  = test['Phrase'].values
sentiment_train = train['Sentiment'].values
num_labels = len(np.unique(sentiment_train))

In [46]:
np.unique(sentiment_train)

array([0, 1, 2, 3, 4])

# **Preprocessing Data**

In [52]:
stop_words = set(stopwords.words('english'))
print(stop_words)

{'herself', "didn't", 'whom', 'your', "couldn't", 'you', "it's", 'them', 'this', 'by', 'up', 'against', 'again', 'i', 'in', 'out', "shouldn't", 'be', 'had', 've', 'am', 'same', 'between', 'o', 'myself', 'are', 'for', 's', 'into', 'most', 'm', 'under', 'where', "hasn't", "don't", 'which', 'that', 'it', 'yourself', 'my', 'his', 'theirs', 'doesn', 'only', "mustn't", 'these', 'they', "wouldn't", 'at', "hadn't", 'there', 'we', 'an', 'no', "you've", "needn't", "she's", 'she', 'been', 'and', 'below', 'ma', 'than', 'own', "that'll", "mightn't", 'few', 'if', 'ain', 'themselves', 'needn', 'when', 'other', 'now', 'do', 'haven', 'hadn', 'should', 'd', 'what', "haven't", "won't", 'yourselves', 'further', 'those', "you'd", 'their', 'very', 'll', 'will', 'hasn', 'who', 'its', 'didn', 'so', 'our', 'has', 'why', 'ourselves', "you're", 'before', 'how', 'yours', 'while', 'does', 'is', 'aren', 'being', 'but', 'from', 'each', 'was', 'did', 'wasn', 'were', 'he', 'after', 'down', 'because', 'or', 'of', 'some

In [51]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [53]:
stop_words.update(['.',',','"',"'",":",';','(',')','[',']','{','}'])
print(stop_words)

{'herself', "didn't", 'whom', 'your', "couldn't", 'you', "it's", 'them', 'this', 'by', 'up', 'against', 'again', 'i', 'in', 'out', "shouldn't", 'be', 'had', 've', 'am', 'same', '[', 'between', 'o', 'myself', 'are', 'for', 's', 'into', 'most', 'm', 'under', 'where', "hasn't", ';', "don't", 'which', 'that', 'it', 'yourself', '.', 'my', 'his', 'theirs', 'doesn', 'only', "mustn't", 'these', 'they', "wouldn't", 'at', '{', "hadn't", "'", 'there', 'we', 'an', 'no', "you've", "needn't", "she's", 'she', 'been', 'and', 'below', 'ma', 'than', 'own', "that'll", "mightn't", 'few', 'if', 'ain', 'themselves', 'needn', 'when', 'other', 'now', 'do', 'haven', 'hadn', 'should', 'd', 'what', "haven't", "won't", 'yourselves', 'further', 'those', "you'd", 'their', 'very', 'll', ':', 'will', 'hasn', 'who', 'its', 'didn', 'so', 'our', 'has', 'why', 'ourselves', "you're", 'before', 'how', 'yours', 'while', 'does', 'is', 'aren', ']', 'being', 'but', 'from', 'each', 'was', 'did', 'wasn', 'were', 'he', 'after', '

In [0]:
stemmer = SnowballStemmer('english')

In [58]:
print("Pre-processing train docs..")
processed_docs_train = []
for index,doc in enumerate(raw_docs_train):
  tokens = word_tokenize(doc)
  filtered = [word for word in tokens if word not in stop_words]
  stemmed = [stemmer.stem(word) for word in filtered]
  processed_docs_train.append(stemmed)

  if index==0:
    print('\n')
    print(doc)
    print('\n')
    print(tokens)
    print('\n')
    print(filtered)
    print('\n')
    print(stemmed)

Pre-processing train docs..


A series of escapades demonstrating the adage that what is good for the goose is also good for the gander , some of which occasionally amuses but none of which amounts to much of a story .


['A', 'series', 'of', 'escapades', 'demonstrating', 'the', 'adage', 'that', 'what', 'is', 'good', 'for', 'the', 'goose', 'is', 'also', 'good', 'for', 'the', 'gander', ',', 'some', 'of', 'which', 'occasionally', 'amuses', 'but', 'none', 'of', 'which', 'amounts', 'to', 'much', 'of', 'a', 'story', '.']


['A', 'series', 'escapades', 'demonstrating', 'adage', 'good', 'goose', 'also', 'good', 'gander', 'occasionally', 'amuses', 'none', 'amounts', 'much', 'story']


['a', 'seri', 'escapad', 'demonstr', 'adag', 'good', 'goos', 'also', 'good', 'gander', 'occasion', 'amus', 'none', 'amount', 'much', 'stori']


In [56]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [60]:
print("Pre-processing the test docs")
processed_docs_test = []
for doc in raw_docs_test:
  tokens = word_tokenize(doc)
  filtered = [word for word in tokens if word not in stop_words]
  stemmed = [stemmer.stem(word) for word in filtered]
  processed_docs_test.append(stemmed)

Pre-processing the test docs


In [0]:
processed_docs_all = np.concatenate((processed_docs_train,processed_docs_test),axis=0)

In [0]:
dictionary = corpora.Dictionary(processed_docs_all)
dictionary_size = len(dictionary.keys())

In [63]:
print("Dictionary size",dictionary_size)

Dictionary size 13759


In [64]:
dictionary[0],dictionary[14]

('a', 'stori')

In [65]:
print("Converting to token ids...")
word_id_train,word_id_len = [], []
for index,doc in enumerate(processed_docs_train):
  word_ids = [dictionary.token2id[word] for word in doc]
  word_id_train.append(word_ids)
  word_id_len.append(len(word_ids))

  if index==0:
    print(doc)
    print(word_ids)
    print(word_id_train)
    print(word_id_len)

Converting to token ids...
['a', 'seri', 'escapad', 'demonstr', 'adag', 'good', 'goos', 'also', 'good', 'gander', 'occasion', 'amus', 'none', 'amount', 'much', 'stori']
[0, 13, 6, 5, 1, 8, 9, 2, 8, 7, 12, 4, 11, 3, 10, 14]
[[0, 13, 6, 5, 1, 8, 9, 2, 8, 7, 12, 4, 11, 3, 10, 14]]
[16]


In [0]:
word_id_test, word_ids = [],[]
for doc in processed_docs_test:
  words_ids = [dictionary.token2id[word] for word in doc]
  word_id_test.append(word_ids)
  word_id_len.append(len(word_ids))

In [68]:
seq_len  = np.round((np.mean(word_id_len) + 2*np.std(word_id_len))).astype(int)
print(np.mean(word_id_len))
print(np.std(word_id_len))
print(seq_len)

2.9884102684032525
3.771268113139097
11


# **Padding Sequences**

In [0]:
word_id_train = sequence.pad_sequences(np.array(word_id_train),maxlen=seq_len)
word_id_test = sequence.pad_sequences(np.array(word_id_test),maxlen=seq_len)
y_train_enc = np_utils.to_categorical(sentiment_train,num_labels)

In [70]:
print(word_id_train)

[[    8     9     2 ...     3    10    14]
 [    0     0     0 ...     1     8     9]
 [    0     0     0 ...     0     0    13]
 ...
 [    0     0     0 ...     0 11849 11850]
 [    0     0     0 ...     0     0 11849]
 [    0     0     0 ...     0     0 11850]]


In [71]:
print(y_train_enc)

[[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 ...
 [0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]]


# **Training RNN LSTM Model**

In [72]:
print("Fitting LSTM")
model = Sequential()
model.add(Embedding(dictionary_size,128))
model.add(Dropout(0.2))
model.add(LSTM(128))
model.add(Dropout(0.2))
model.add(Dense(num_labels))
model.add(Activation('softmax'))

model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

Fitting LSTM


In [73]:
model.fit(word_id_train,y_train_enc,epochs=3,batch_size=256,verbose=1)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/indexed_slices.py:434: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "


Epoch 1/3
156060/156060 [==============================] - 64s 410us/step - loss: 1.0002 - accuracy: 0.5983
Epoch 2/3
156060/156060 [==============================] - 64s 409us/step - loss: 0.8268 - accuracy: 0.6601
Epoch 3/3
156060/156060 [==============================] - 64s 409us/step - loss: 0.7710 - accuracy: 0.6807


# **Using Convolutional Neural Network (CNN) + LSTM**

In [76]:
print("Fitting LSTM")
model = Sequential()
model.add(Embedding(dictionary_size,128))
model.add(Conv1D(filters=32,kernel_size=3,padding='same',activation='relu'))
model.add(MaxPooling1D(pool_size=2))

model.add(LSTM(128,dropout=0.2,recurrent_dropout=0.2))
model.add(Dense(num_labels,activation='softmax'))
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

Fitting LSTM


In [77]:
model.fit(word_id_train,y_train_enc,epochs=3,batch_size=256,verbose=1)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/indexed_slices.py:434: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "


Epoch 1/3
156060/156060 [==============================] - 39s 252us/step - loss: 1.0188 - accuracy: 0.5915
Epoch 2/3
156060/156060 [==============================] - 39s 250us/step - loss: 0.8312 - accuracy: 0.6588
Epoch 3/3
156060/156060 [==============================] - 39s 253us/step - loss: 0.7709 - accuracy: 0.6809


In [0]:
test_pred = model.predict_classes(word_id_test)

In [79]:
test_pred

array([2, 2, 2, ..., 2, 2, 2])

In [0]:
test['Sentiment'] = test_pred.reshape(-1,1)
header = ['PhraseId','Sentiment']
test.to_csv('/content/drive/My Drive/data/submission_lstm_cnn.csv',columns=header,index=False,header=True)